---
name: sanity tests

on: [workflow_call]  # allow this workflow to be called from other workflows

jobs:
  sanity:
    uses: ansible-network/github_actions/.github/workflows/sanity.yml@main
    with:
      matrix_include: "[]"
      matrix_exclude: >-
          [
            {
              "ansible-version": "stable-2.9"
            },
            {
              "ansible-version": "stable-2.12",
              "python-version": "3.7"
            },
            {
              "ansible-version": "stable-2.12",
              "python-version": "3.11"
            }
          ]
